In [31]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/data.csv', sep=';')

In [32]:
df.rename(columns={'Nacionality':'Nationality',
                   'Daytime/evening attendance\t':'Daytime/Evening Att.',
                   'Educational special needs':'Special Needs',
                   'Tuition fees up to date':'Tuition Paid',
                   'Scholarship holder':'Scholarship'},
          inplace=True)
df

,Marital status,Application mode,Application order,Course,Daytime/Evening Att.,Previous qualification,Previous qualification (grade),Nationality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4419,1,1,6,9773,1,1,125.0,1,1,1,...,0,6,8,5,12.666667,0,15.5,2.8,-4.06,Graduate
4420,1,1,2,9773,1,1,120.0,105,1,1,...,0,6,6,2,11.000000,0,11.1,0.6,2.02,Dropout
4421,1,1,1,9500,1,1,154.0,1,37,37,...,0,8,9,1,13.500000,0,13.9,-0.3,0.79,Dropout
4422,1,1,1,9147,1,1,180.0,1,37,37,...,0,5,6,5,12.000000,0,9.4,-0.8,-3.12,Graduate
4423,1,10,1,9773,1,1,152.0,22,38,37,...,0,6,6,6,13.000000,0,12.7,3.7,-1.70,Graduate

In [33]:
daytime_att = df['Daytime/Evening Att.'] == 0
evening_att = df['Daytime/Evening Att.'] == 1
pd.crosstab(df['Target'], df['Daytime/Evening Att.'])

Daytime/Evening Att.    0     1
Target
Dropout               207  1214
Enrolled               75   719
Graduate              201  2008

In [34]:
non_displaced = df['Displaced'] == 0 
displaced = df['Displaced'] == 1
pd.crosstab(df['Target'], df['Displaced'])

Displaced    0     1
Target
Dropout    752   669
Enrolled   361   433
Graduate   885  1324

In [35]:
non_debtor = df['Debtor'] == 0
debtor = df['Debtor'] == 1
pd.crosstab(df['Target'], df['Debtor'])

Debtor       0    1
Target
Dropout   1109  312
Enrolled   704   90
Graduate  2108  101

In [36]:
tuition_unpaid = df['Tuition Paid'] == 0
tuition_paid = df['Tuition Paid'] == 1
pd.crosstab(df['Target'], df['Tuition Paid'])

Tuition Paid    0     1
Target
Dropout       457   964
Enrolled       42   752
Graduate       29  2180

In [37]:
male = df['Gender'] == 0
female = df['Gender'] == 1
pd.crosstab(df['Target'], df['Gender'])

Gender       0    1
Target
Dropout    720  701
Enrolled   487  307
Graduate  1661  548

In [38]:
no_scholarship = df['Scholarship'] == 0
scholarship = df['Scholarship'] == 1
pd.crosstab(df['Target'], df['Scholarship'])

Scholarship     0    1
Target
Dropout      1287  134
Enrolled      664  130
Graduate     1374  835

In [39]:
non_international = df['International'] == 0
international = df['International'] == 1
pd.crosstab(df['Target'], df['Scholarship'])

Scholarship     0    1
Target
Dropout      1287  134
Enrolled      664  130
Graduate     1374  835

In [40]:
df['Target'] = df['Target'].replace({'Dropout':0, 'Enrolled':-1, 'Graduate':1})
df['Target']

0       0
1       1
2       0
3       1
4       1
       ..
4419    1
4420    0
4421    0
4422    1
4423    1
Name: Target, Length: 4424, dtype: object